# Generated by Django 3.2.6 on 2021-08-11 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_note_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_time',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
