# Generated by Django 3.2.6 on 2021-08-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210811_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='default text', max_length=255),
            preserve_default=False,
        ),
    ]
